name: Format

on:
  workflow_dispatch:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.10'

      - uses: psf/black@stable
        with:
          options: "--check --color --verbose"
          src: "./src"
